[package]
name = "lander"
version = "0.1.0"
edition = "2021"
authors = [ "Brandon Grooters" ]
repository = "https://github.com/wasmco/lander"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.14.2"
